[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

# El plugin de Next.js en Netlify es autodetectado en proyectos Next recientes.
# Si lo prefieres explícito, instala @netlify/plugin-nextjs y descomenta:
#
# [plugins]
#   package = "@netlify/plugin-nextjs"
